In [1]:
price_a=[8.7,8.91,8,71]


In [2]:
8.91/8.7


1.024137931034483

In [3]:
import numpy as np

In [4]:
price=np.array([8.7,8.91,8.71])

In [5]:
price

array([8.7 , 8.91, 8.71])

In [7]:
price[1:]

array([8.91, 8.71])

In [8]:
price[:-1]

array([8.7 , 8.91])

In [9]:
price[1:]/price[:-1]-1

array([ 0.02413793, -0.02244669])

In [10]:
import pandas as pd

In [14]:
prices=pd.DataFrame({"BLUE":[8.7 , 8.91, 8.71,8.43,8.73]
                     ,
                    "ORANGE":[10.66,11.08,10.71,11.59,12.11]
                    })

In [15]:
prices

BLUE  ORANGE
0  8.70   10.66
1  8.91   11.08
2  8.71   10.71
3  8.43   11.59
4  8.73   12.11

In [16]:
prices.iloc[1:]

BLUE  ORANGE
1  8.91   11.08
2  8.71   10.71
3  8.43   11.59
4  8.73   12.11

In [19]:
prices.iloc[:-1]

BLUE  ORANGE
0  8.70   10.66
1  8.91   11.08
2  8.71   10.71
3  8.43   11.59

In [20]:
prices.iloc[1:]/prices.iloc[:-1]

BLUE  ORANGE
0   NaN     NaN
1   1.0     1.0
2   1.0     1.0
3   1.0     1.0
4   NaN     NaN

In [21]:
prices.iloc[1:].values/prices.iloc[:-1]-1

BLUE    ORANGE
0  0.024138  0.039400
1 -0.022447 -0.033394
2 -0.032147  0.082166
3  0.035587  0.044866

In [22]:
prices.iloc[1:].values/prices.iloc[:-1].values

array([[1.02413793, 1.03939962],
       [0.97755331, 0.9666065 ],
       [0.96785304, 1.0821662 ],
       [1.03558719, 1.04486626]])

In [23]:
prices

BLUE  ORANGE
0  8.70   10.66
1  8.91   11.08
2  8.71   10.71
3  8.43   11.59
4  8.73   12.11

In [24]:
prices.shift(1)

BLUE  ORANGE
0   NaN     NaN
1  8.70   10.66
2  8.91   11.08
3  8.71   10.71
4  8.43   11.59

In [25]:
prices/prices.shift(1)

BLUE    ORANGE
0       NaN       NaN
1  1.024138  1.039400
2  0.977553  0.966606
3  0.967853  1.082166
4  1.035587  1.044866

In [26]:
prices

BLUE  ORANGE
0  8.70   10.66
1  8.91   11.08
2  8.71   10.71
3  8.43   11.59
4  8.73   12.11

In [27]:
prices.pct_change()

BLUE    ORANGE
0       NaN       NaN
1  0.024138  0.039400
2 -0.022447 -0.033394
3 -0.032147  0.082166
4  0.035587  0.044866

In [30]:
np.prod(prices)

BLUE       49688.619396
ORANGE    177547.276592
dtype: float64

In [31]:
# np.prod() multiplies all the elements with each other

In [34]:
## Annualization


In [36]:
rm=0.01
(1+rm)**12-1

0.12682503013196977

In [37]:
rq=0.04
(1+rq)**4-1

0.1698585600000002